name: Build Parser 2GIS Enhanced

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller setuptools wheel
        pip install -e .
    
    - name: Test installation
      run: |
        python -c "from parser_2gis import main; print('Module loaded successfully')"
    
    - name: Build Windows executable
      run: |
        mkdir dist
        pyinstaller --onefile ^
          --name parser-2gis ^
          --distpath dist/windows ^
          --add-data "parser_2gis/data/cities.json;parser_2gis/data" ^
          --add-data "parser_2gis/data/rubrics.json;parser_2gis/data" ^
          --hidden-import pydantic ^
          --hidden-import psutil ^
          --hidden-import openpyxl ^
          --collect-submodules parser_2gis ^
          --console ^
          parser-2gis.py
    
    - name: Copy additional files
      run: |
        copy README_RELEASE.md "dist/windows/README.md"
        echo @echo off > "dist/windows/run-example.bat"
        echo parser-2gis.exe -i "https://2gis.ru/moscow/search/кафе" -o cafes.csv -f csv --parser.max-records 50 >> "dist/windows/run-example.bat"
    
    - name: Create Windows archive
      run: |
        cd dist
        powershell -command "Compress-Archive -Path 'windows' -DestinationPath 'parser-2gis-enhanced-windows.zip'"
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: parser-2gis-windows
        path: dist/parser-2gis-enhanced-windows.zip
  
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      run: |
        brew install --cask google-chrome
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller setuptools wheel
        pip install -e .
    
    - name: Test installation
      run: |
        python -c "from parser_2gis import main; print('Module loaded successfully')"
    
    - name: Build macOS executable
      run: |
        mkdir -p dist
        pyinstaller --onefile \
          --name parser-2gis \
          --distpath dist/macos \
          --add-data "parser_2gis/data/cities.json:parser_2gis/data" \
          --add-data "parser_2gis/data/rubrics.json:parser_2gis/data" \
          --hidden-import pydantic \
          --hidden-import psutil \
          --hidden-import openpyxl \
          --collect-submodules parser_2gis \
          --console \
          parser-2gis.py
    
    - name: Copy additional files
      run: |
        cp README_RELEASE.md "dist/macos/README.md"
        echo '#!/bin/bash' > "dist/macos/run-example.sh"
        echo './parser-2gis -i "https://2gis.ru/moscow/search/кафе" -o cafes.csv -f csv --parser.max-records 50' >> "dist/macos/run-example.sh"
        chmod +x "dist/macos/run-example.sh"
        chmod +x "dist/macos/parser-2gis"
    
    - name: Create macOS archive
      run: |
        cd dist
        tar -czf parser-2gis-enhanced-macos.tar.gz macos/
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: parser-2gis-macos
        path: dist/parser-2gis-enhanced-macos.tar.gz
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          parser-2gis-windows/parser-2gis-enhanced-windows.zip
          parser-2gis-macos/parser-2gis-enhanced-macos.tar.gz
        body: |
          # Parser 2GIS Enhanced Edition
          
          ## 🆕 Новые возможности:
          - ✅ **67 колонок данных** включая телефоны, email, социальные сети
          - ✅ **Автоматическая пагинация** для сбора данных с нескольких страниц
          - ✅ **Видимый браузер** по умолчанию для наблюдения процесса
          - ✅ **Улучшенные настройки** для максимального сбора информации
          
          ## 📥 Скачать:
          - **Windows**: `parser-2gis-enhanced-windows.zip`
          - **macOS**: `parser-2gis-enhanced-macos.tar.gz`
          
          ## 🚀 Быстрый старт:
          ```bash
          # Распакуйте архив и запустите:
          ./parser-2gis -i "https://2gis.ru/moscow/search/кафе" -o cafes.csv -f csv --parser.max-records 100
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}