name: Development Build

on:
  push:

jobs:
  build:
    name: Development Build

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            dist: linux
            ext:

          - os: macos-13
            dist: macos
            ext:

          - os: macos-14
            dist: macos-arm
            ext:

          - os: windows-2022
            dist: windows
            ext: .exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Installing main dependencies..."
        python -m pip install -e .[gui,dev] -v
        echo "Dependencies installed successfully"
        # Replace pydantic with no-binary version to lightweight target binary a bit
        # python -m pip uninstall -y pydantic
        # python -m pip install --no-binary pydantic pydantic>=1.9.0

    - name: Test installation
      run: |
        echo "Testing Python import..."
        python test_compatibility.py
        echo "Testing setup.py..."
        python setup.py --version

    - name: Build standalone app
      run: |
        python setup.py build_standalone

    - name: Upload distributive
      uses: actions/upload-artifact@v4
      with:
        name: Parser2GIS-dev-${{matrix.dist}}
        path: dist/Parser2GIS${{matrix.ext}}
        retention-days: 30